###
# Configuration for Vagrant
###
name: wpsv
#production:
  # This is used to automatically fetch data from a staging/production environment
  #domain: example.seravo.com
  #ssh_port: 12345
  #url: https://example.seravo.com
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications
  domains:
    - wpsv.dev
  # If you want to use zeroconf (.local domains) in your network you can use this.
  #avahi: true
